export enum InstrumentCapability {
    CONTEXT_TRAVERSAL = "CONTEXT_TRAVERSAL",
    LIST_CONTENT      = "LIST_CONTENT",
    READ_CONTENT      = "READ_CONTENT",
    WRITE_CONTENT     = "WRITE_CONTENT",
    UPDATE_CONTENT    = "UPDATE_CONTENT",
    DELETE_CONTENT    = "DELETE_CONTENT",
}